package com.mrptech.giveLife.model;

// Generated May 13, 2015 10:44:21 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Hospital generated by hbm2java
 */
@Entity
@Table(name = "HOSPITAL")
@NamedQuery(name="Hospital.findAll",query="SELECT H.hospitalName,H.hospitalLoc FROM Hospital H")

public class Hospital implements java.io.Serializable {

	private BigDecimal hospitalId;
	private String hospitalName;
	private String hospitalLoc;
	private String status;
	private String country;
	private String state;
	private String city;

	public Hospital() {
	}

	public Hospital(BigDecimal hospitalId) {
		this.hospitalId = hospitalId;
	}

	

	@Id
	@Column(name = "HOSPITAL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(BigDecimal hospitalId) {
		this.hospitalId = hospitalId;
	}

	@Column(name = "HOSPITAL_NAME", length = 30)
	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	@Column(name = "HOSPITAL_LOC", length = 20)
	public String getHospitalLoc() {
		return this.hospitalLoc;
	}

	public void setHospitalLoc(String hospitalLoc) {
		this.hospitalLoc = hospitalLoc;
	}

	@Column(name = "STATUS", length = 30)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COUNTRY", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "STATE", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "CITY", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
