package com.mrptech.giveLife.model;

// Generated May 13, 2015 10:44:21 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class User implements java.io.Serializable {

	private BigDecimal accountId;
	private String firstName;
	private String lastName;
	private String email;
	private Date dob;
	private String bloodGroup;
	private BigDecimal mobileNo;
	private String country;
	private String state;
	private String district;
	private String city;
	private String col1;
	private BigDecimal col2;
	private BigDecimal col3;
	private Date col4;
	private String col5;
	private String col6;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Set<UserRequest> userRequests = new HashSet<UserRequest>(0);
	private Set<UserDonor> userDonors = new HashSet<UserDonor>(0);

	public User() {
	}

	public User(BigDecimal accountId, Date createdOn, String createdBy) {
		this.accountId = accountId;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	

	@Id
	@Column(name = "ACCOUNT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAccountId() {
		return this.accountId;
	}

	public void setAccountId(BigDecimal accountId) {
		this.accountId = accountId;
	}

	@Column(name = "FIRST_NAME", length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 7)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "BLOOD_GROUP", length = 10)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "MOBILE_NO", precision = 22, scale = 0)
	public BigDecimal getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(BigDecimal mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "COUNTRY", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "STATE", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "DISTRICT", length = 30)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "CITY", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "COL1", length = 30)
	public String getCol1() {
		return this.col1;
	}

	public void setCol1(String col1) {
		this.col1 = col1;
	}

	@Column(name = "COL2", precision = 22, scale = 0)
	public BigDecimal getCol2() {
		return this.col2;
	}

	public void setCol2(BigDecimal col2) {
		this.col2 = col2;
	}

	@Column(name = "COL3", precision = 22, scale = 0)
	public BigDecimal getCol3() {
		return this.col3;
	}

	public void setCol3(BigDecimal col3) {
		this.col3 = col3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COL4", length = 7)
	public Date getCol4() {
		return this.col4;
	}

	public void setCol4(Date col4) {
		this.col4 = col4;
	}

	@Column(name = "COL5", length = 30)
	public String getCol5() {
		return this.col5;
	}

	public void setCol5(String col5) {
		this.col5 = col5;
	}

	@Column(name = "COL6", length = 30)
	public String getCol6() {
		return this.col6;
	}

	public void setCol6(String col6) {
		this.col6 = col6;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_ON", nullable = false, length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFIED_ON", length = 7)
	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	@Column(name = "MODIFIED_BY", length = 30)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserRequest> getUserRequests() {
		return this.userRequests;
	}

	public void setUserRequests(Set<UserRequest> userRequests) {
		this.userRequests = userRequests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserDonor> getUserDonors() {
		return this.userDonors;
	}

	public void setUserDonors(Set<UserDonor> userDonors) {
		this.userDonors = userDonors;
	}

}
