package com.mrptech.giveLife.model;

// Generated May 13, 2015 10:44:21 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserDonor generated by hbm2java
 */
@Entity
@Table(name = "USER_DONOR")
@NamedQuery(name="DONOR_LIST",query="SELECT new com.mrptech.giveLife.dto.SeekerDto(u.mobileNo, ud.donorId, u.accountId) FROM UserDonor ud,User u "
		+ "WHERE ud.status='ACTIVE' and u.district=? and u.bloodGroup=?  and ud.user.accountId=u.accountId ")
public class UserDonor implements java.io.Serializable {

	private BigDecimal donorId;
	private User user;
	private Date donorReqTime;
	private String status;
	private Double rating;
	private Set<UserRequest> userRequests = new HashSet<UserRequest>(0);

	public UserDonor() {
	}

	public UserDonor(BigDecimal donorId, User user) {
		this.donorId = donorId;
		this.user = user;
	}

	public UserDonor(BigDecimal donorId, User user, Date donorReqTime,
			String status, Double rating, Set<UserRequest> userRequests) {
		this.donorId = donorId;
		this.user = user;
		this.donorReqTime = donorReqTime;
		this.status = status;
		this.rating = rating;
		this.userRequests = userRequests;
	}

	@Id
	@Column(name = "DONOR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getDonorId() {
		return this.donorId;
	}

	public void setDonorId(BigDecimal donorId) {
		this.donorId = donorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DONOR_REQ_TIME", length = 7)
	public Date getDonorReqTime() {
		return this.donorReqTime;
	}

	public void setDonorReqTime(Date donorReqTime) {
		this.donorReqTime = donorReqTime;
	}

	@Column(name = "STATUS", length = 30)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "RATING", precision = 2, scale = 0)
	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userDonor")
	public Set<UserRequest> getUserRequests() {
		return this.userRequests;
	}

	public void setUserRequests(Set<UserRequest> userRequests) {
		this.userRequests = userRequests;
	}

}
